name: Update ril100 data
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install nix
        uses: cachix/install-nix-action@v30

      - name: Run update script
        run: nix develop --command ./scripts/update-data.sh
        env:
          GH_TOKEN: ${{ github.token }}
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
